/*
 * Catalog
 * Catalog
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@gb.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Book;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CatalogApi
 */
@Ignore
public class CatalogApiTest {

    private final CatalogApi api = new CatalogApi();

    
    /**
     * get catalog
     *
     * Get list of products
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCatalogTest() throws ApiException {
        String author = null;
        List<Book> response = api.getCatalog(author);

        // TODO: test validations
    }
    
    /**
     * update book
     *
     * Update exist book or create new
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updBookTest() throws ApiException {
        Book book = null;
        List<Book> response = api.updBook(book);

        // TODO: test validations
    }
    
}
